language: cpp

sudo: required

dist: bionic

addons:
  apt:
    packages:
      - cmake
      - gcc
      - g++
      - libjsoncpp-dev
      - uuid-dev
      - zlib1g-dev
      - openssl
      - libssl-dev
      - mariadb-client
      - mariadb-server
      - build-essential
      - libboost-all-dev

services:
  - mysql

before_install:
  - wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
  - tar xf release-1.10.0.tar.gz
  - cd googletest-release-1.10.0
  - cmake .
  - make
  - sudo make install
  - cd -

script:
  - git submodule update --init --recursive
  - mkdir build 
  - cd build
  - cmake ..
  - make