# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:focal

    steps:
      - checkout
      - run: |
          sudo apt install cmake gcc g++ libjsoncpp-dev uuid-dev zlib1g-dev openssl \
          libssl-dev mariadb-client mariadb-server build-essential libboost-all-dev
      - run: |
          wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
          tar xf release-1.10.0.tar.gz -C ~/
          cd ~/googletest-release-1.10.0
          cmake .
          make
          sudo make install
          cd -
      - run: |
          git submodule update --init --recursive
          mkdir build
          cd build
          cmake ..
          make
          mkdir shorturl
          mv etc/ static/ ShortURL shorturl
          tar Jcvf shorturl.tar.xz shorturl/
          